feat: add registration user
dmytro-senko/book-store pull request #9
Opened 2024-03-06 16:39 UTC by dmytro-senko

2024-03-06 19:18 UTC, olekskov requested changes

2024-03-06 19:18 UTC, olekskov commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
It's a bad practice to use both liquibase and hibernate as sources for DB structure.
Please return back to validate strategy

2024-03-07 10:54 UTC, kozhukhovsky approved these changes

2024-03-07 10:54 UTC, kozhukhovsky commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-create-users-table.yaml
```suggestion
      file: db/changelog/changes/02-create-users-table.yaml
      
```

2024-03-07 11:37 UTC, merged